name: teamspeak3
description: Create teamspeak3 bots in dart.
version: 1.0.3
homepage: https://github.com/Hexer10/TeamSpeak3-Library
author: Mattia <hexer504@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
